# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 27de3d1efc125f33e7dab539a547c1e59311277bf04a82f2046f5282a5b6c7acec8a54043ce91d6cba2f34d14927033ccf807494e3a1895191efff506604a1d9

test:
  secret_key_base: 29815e21f890e9f03a4154fdb1e098a3098ee31cbe8fd3acdecb4e8a4048c5fd3e4a0c1ffe2aca61f628c3d42ae1ec6c0ed286dd13911615ea8000e3a48a3d9d

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
  RAILS_ENV=production rake secret
